# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v9.2.0
    
    - name: Caching
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          server
        key: ${{ runner.os }}-${{ hashFiles('go.mod') }}

    - name: Build
      if: steps.cache.outputs.cache-hit != true
      run: go build -v server.go
    
    - name: debug
      run: which go

    - name: Test
      run: go test -v ./...
  
  code-sec-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install govulcheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      
      - name: run scanner
        run: govulncheck ./...
